name: Re-Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The minecraft version to re-release'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: gradle:8.1.0-jdk17
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - run: gradle build publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          FORCE_PUBLISH: ${{ github.event.inputs.version }}